%SETSPEC Set spectrum for pseudo-Euclidean dataset or mapping
%
%   B = SETSPEC(A,SPEC)
%   B = A*SETSPEC([],SPEC);
%
% INPUT
%   A    Dataset
%   SPEC Spectrum, ranked eigenvalues of the pseudo-Euclidean mapping
%
% OUTPUT
%   B   PE dataset
%
% DESCRIPTION
% In the computation of a pseudo-Euclidean embedding by PE_EM a set of
% eigenvalues is encountered that is partially positive and partially
% negative. The ranked set of eigenvalues, from most positive to most
% negative is called the spectrum. It characterizes the PE embedding and
% the original dissimilarity matrix. This routines stores this spectrum in
% a PE dataset generated by such a mapping. It may be retrieved by GETSPEC
% and plotted by PLOTSPEC
%
% SEE ALSO
% DATASETS, MAPPINGS, PE_EM, GETSPEC, PLOTSPEC
